// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu4Ct9UeWBlqSftfjvZlk1Ks6q7ExBvN8',
    appId: '1:212445563827:web:25331fc3c282af9b2459c6',
    messagingSenderId: '212445563827',
    projectId: 'engineeringhub-72946',
    authDomain: 'engineeringhub-72946.firebaseapp.com',
    storageBucket: 'engineeringhub-72946.appspot.com',
    measurementId: 'G-6F6ZL7MJBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTSsvtBeGZl7CSRW-WvvWEO4b2k_WOytE',
    appId: '1:212445563827:android:792c99d2870f3c572459c6',
    messagingSenderId: '212445563827',
    projectId: 'engineeringhub-72946',
    storageBucket: 'engineeringhub-72946.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnlQEduozb13s0w4hGSIhAsq0qetanWjg',
    appId: '1:212445563827:ios:44b5f7ab080ff9eb2459c6',
    messagingSenderId: '212445563827',
    projectId: 'engineeringhub-72946',
    storageBucket: 'engineeringhub-72946.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnlQEduozb13s0w4hGSIhAsq0qetanWjg',
    appId: '1:212445563827:ios:3856b44a46be2bf42459c6',
    messagingSenderId: '212445563827',
    projectId: 'engineeringhub-72946',
    storageBucket: 'engineeringhub-72946.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
